# Generated by Django 3.0.6 on 2020-05-15 17:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news_app', '0002_postvotes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostVotes',
            new_name='Vote',
        ),
    ]
